### ISSUE TITLE
В форму не возвращается "Заголовок" после удаления в настройках

### ISSUE THREAD

**Issue by DaddyDorset** [artikus11/art-woo-order-one-click#9]
Если в настройках плагина удалить поле "Заголовок" из отображения в форме заказа, а потом снова его включить, то он так и не появляется там снова.
Поле "Цена" работает нормально.
Поле "Изображение" не проверял.

**Comment by artikus11** [comment]
@DaddyDorset на новых версиях баг повторяется? А то я себя не вижу ничего такого

**Comment by DaddyDorset** [comment]
Приветствую! Я, увы, отказался от использования плагина, так что сходу
ответить не могу. Надо воспроизвести и тогда смогу сказать, но быстро не
получится -- к концу недели разве что время поковырять будет. Миль пардон,
как говорится.

вт, 12 февр. 2019, 14:19 Artem Abramovich notifications@github.com:
